from __future__ import annotations

from enum import StrEnum


class OrderAction(StrEnum):
    BUY = "BUY"
    SELL = "SELL"
    BUY_LIMIT = "BUY_LIMIT"
    SELL_LIMIT = "SELL_LIMIT"
    BUY_STOP = "BUY_STOP"
    SELL_STOP = "SELL_STOP"
    CLOSE = "CLOSE"
    MODIFY = "MODIFY"
    CANCEL = "CANCEL"


class AccountType(StrEnum):
    DEMO = "DEMO"
    LIVE = "LIVE"
    UNKNOWN = "UNKNOWN"


class ConfirmationPolicy(StrEnum):
    NONE = "NONE"
    SINGLE_CONFIRMATION = "SINGLE_CONFIRMATION"
    DOUBLE_CONFIRMATION = "DOUBLE_CONFIRMATION"


class ExecutionStatus(StrEnum):
    REQUESTED = "REQUESTED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"
    DRY_RUN = "DRY_RUN"


class ExecutionState(StrEnum):
    IDLE = "IDLE"
    SIGNAL_RECEIVED = "SIGNAL_RECEIVED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    LOCATING_TERMINAL = "LOCATING_TERMINAL"
    PREPARING_UI = "PREPARING_UI"
    ORDER_READY = "ORDER_READY"
    EXECUTING = "EXECUTING"
    EXECUTION_DETECTED = "EXECUTION_DETECTED"
    VERIFYING = "VERIFYING"
    SUCCESS = "SUCCESS"
    DRY_RUN_COMPLETED = "DRY_RUN_COMPLETED"
    INVALID_SIGNAL = "INVALID_SIGNAL"
    TERMINAL_NOT_FOUND = "TERMINAL_NOT_FOUND"
    WINDOW_NOT_READY = "WINDOW_NOT_READY"
    SYMBOL_NOT_FOUND = "SYMBOL_NOT_FOUND"
    UI_ELEMENT_NOT_FOUND = "UI_ELEMENT_NOT_FOUND"
    ORDER_REJECTED = "ORDER_REJECTED"
    TIMEOUT = "TIMEOUT"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    UNKNOWN_EXECUTION = "UNKNOWN_EXECUTION"
    UNKNOWN_STATE = "UNKNOWN_STATE"
